name: Deploy Azure Web App with Bicep

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Bicep CLI
        run: |
          az bicep install

     # - name: Build Bicep to ARM template
     #   run: |
     #     az bicep build --file ./infra/webapp.bicep --outfile ./infra/webapp.json
        
      #- name: Build Bicep to ARM template for Resource Groups
      #  run: |
      #    az bicep build --file ./infra/resourcegroups.bicep --outfile ./infra/resourcegroups.json

      - name: Deploy Resource Groups Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: 'subscription' # Corrected scope
          region: northeurope # Specify the region for the resource group
          template: ./infra/resourcegroup.bicep # Corrected file name
          parameters: |
            rgName=infra
            rgLocation=northeurope
          deploymentName: resourcegroups-deployment
          failOnStdErr: true

      - name: Deploy Web App Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: 'resourceGroup'
          resourceGroupName: infra
          template: ./infra/webapp.bicep
          parameters: |
            webAppName=MemberCare
          deploymentName: webapp-deployment
